In [6]:
from pandas import Series,DataFrame

In [7]:
import pandas as pd
import numpy as np

# Pandas的数据结构介绍

## Series

>Series是类似于一维数组的对象， 由一组数据以及一组与之相关的数据标签组成

In [8]:
obj = pd.Series([4,7,-5,3])

In [9]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

1. Series的字符串表现形式为，索引在左边，值在右边，如果没有为数据指定索引，会自动创建一个0，N-1的整数型索引。
2. 过Series的values和index属性获取对应的值与索引


In [11]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [14]:
obj.index

RangeIndex(start=0, stop=4, step=1)

自定义索引

In [15]:
obj2 = Series([4,7,-5,3],index = ['d','a','b','c'])

In [16]:
obj2

d    4
a    7
b   -5
c    3
dtype: int64

In [17]:
obj2.index

Index(['d', 'a', 'b', 'c'], dtype='object')

通过索引的方式取一个或一组值

In [18]:
obj2['a']

7

In [19]:
obj2['d'] = 6

In [21]:
obj2

d    6
a    7
b   -5
c    3
dtype: int64

In [22]:
obj2[['c','a','b']]

c    3
a    7
b   -5
dtype: int64

保留了Numpy的数组运算

In [23]:
obj2

d    6
a    7
b   -5
c    3
dtype: int64

In [25]:
obj2[obj2 > 0]

d    6
a    7
c    3
dtype: int64

In [26]:
obj2 * 2

d    12
a    14
b   -10
c     6
dtype: int64

可以把Series看成是一个定长的有序字典

In [30]:
'b' in obj2

True

通过字典创建Series

In [2]:
sdata = {'Ohio':35000,'Texas':71000,'Oregon':16000,'Utah':5000}

In [8]:
obj3 = Series(sdata)

In [9]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [10]:
statas = ['Cali','Ohio','Oregon','Texas']

In [11]:
obj4 = Series(sdata,index=statas)

In [12]:
obj4

Cali          NaN
Ohio      35000.0
Oregon    16000.0
Texas     71000.0
dtype: float64

1. sdata 中和states索引匹配的三个值被找出，NaN表示not a number
2. pandas中 isnull 和 notnull函数可用于检测缺失数据

In [13]:
pd.isnull(obj4)

Cali       True
Ohio      False
Oregon    False
Texas     False
dtype: bool

In [14]:
pd.notnull(obj4)

Cali      False
Ohio       True
Oregon     True
Texas      True
dtype: bool

Series 在算数运算中会自动对齐不同索引的数据

In [15]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [16]:
obj4

Cali          NaN
Ohio      35000.0
Oregon    16000.0
Texas     71000.0
dtype: float64

In [17]:
obj3 + obj4

Cali           NaN
Ohio       70000.0
Oregon     32000.0
Texas     142000.0
Utah           NaN
dtype: float64

Series对象及其索引都有一个name属性

In [18]:
obj4.name = 'population'

In [19]:
obj4.index.name = 'state'

In [47]:
obj4

state
Cali          NaN
Ohio      35000.0
Oregon    16000.0
Texas     71000.0
Name: population, dtype: float64

In [48]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [55]:
obj.index = ['a','b','c','d']

In [56]:
obj

a    4
b    7
c   -5
d    3
dtype: int64

## DataFrame

> DataFrame是一个表格型的数据结构，既有行索引也有列所以，可以被看做由Series组成的字典

传入一个等长列表或Numpy数组组成字典

In [57]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada'],
       'year':[2000,2001,2002,2001,2002],
       'pop':[1.5,1.7,3.6,2.4,2.9]}

In [58]:
frame = DataFrame(data)

In [60]:
frame #所有列按序排列

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [61]:
#按照指定顺序排列
DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [62]:
#传入的列找不到数据，输出NAN
frame2 = DataFrame(data,columns=['year','state','pop','debt'],index=['one','two','three','four','five'])

In [63]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [64]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [65]:
# 通过类似字典取值的方式将DataFrame的列获取为一个Series
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [68]:
# 取行可以用索引字段ix
frame2.ix['three']

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  


year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [70]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [71]:
# 列通过赋值的方式修改
frame2['debt'] = 16

In [72]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5    16
two    2001    Ohio  1.7    16
three  2002    Ohio  3.6    16
four   2001  Nevada  2.4    16
five   2002  Nevada  2.9    16

In [78]:
frame2['debt'] = np.arange(5)

In [79]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4

In [80]:
# 将Series赋值给某个列时，会精确匹配DataFrame的索引，空位会被填上缺失值
val = Series([-1.2,-1.5,-1.6],['one','two','three'])

In [81]:
frame2['debt'] = val

In [82]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  -1.2
two    2001    Ohio  1.7  -1.5
three  2002    Ohio  3.6  -1.6
four   2001  Nevada  2.4   NaN
five   2002  Nevada  2.9   NaN

In [84]:
# 给不存在的列赋值，会创建一个新列
frame2['eastern'] = frame2.state == 'Ohio'

In [85]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5  -1.2     True
two    2001    Ohio  1.7  -1.5     True
three  2002    Ohio  3.6  -1.6     True
four   2001  Nevada  2.4   NaN    False
five   2002  Nevada  2.9   NaN    False

In [86]:
#del 可以删除列
del frame2['eastern']

In [87]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

**注意：**对索引方式返回的列都是  视图，所以对返回的Series所做的修改都会反映到源DataFrame上

In [88]:
temp_series = frame2['debt']

In [89]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  -1.2
two    2001    Ohio  1.7  -1.5
three  2002    Ohio  3.6  -1.6
four   2001  Nevada  2.4   NaN
five   2002  Nevada  2.9   NaN

In [90]:
temp_series

one     -1.2
two     -1.5
three   -1.6
four     NaN
five     NaN
Name: debt, dtype: float64

In [91]:
temp_series['one'] = 10000

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [92]:
temp_series

one      10000.0
two         -1.5
three       -1.6
four         NaN
five         NaN
Name: debt, dtype: float64

In [94]:
frame2  # 显然修改了源frame2的值

year   state  pop     debt
one    2000    Ohio  1.5  10000.0
two    2001    Ohio  1.7     -1.5
three  2002    Ohio  3.6     -1.6
four   2001  Nevada  2.4      NaN
five   2002  Nevada  2.9      NaN

嵌套字典传递给DataFrame
> 外层字典的键作为列，内层键作为行索引

In [95]:
pop = {'Ben':{2001:2.4,2002:2.9},
      'Peter':{2000:1,2001:2.2,2002:3.3}}

In [96]:
frame3 = DataFrame(pop)

In [97]:
frame3

Ben  Peter
2000  NaN    1.0
2001  2.4    2.2
2002  2.9    3.3

In [101]:
frame3.T

2000  2001  2002
Ben     NaN   2.4   2.9
Peter   1.0   2.2   3.3

显示的指定索引
书上是
```
DataFrame(pop,index=[2001,2002,2003])
```报错



用如下方法：

In [111]:
DataFrame(pop,index=pd.Series([2001,2002,2003]))

Ben  Peter
2001  2.4    2.2
2002  2.9    3.3
2003  NaN    NaN

In [112]:
frame3

Ben  Peter
2000  NaN    1.0
2001  2.4    2.2
2002  2.9    3.3

In [124]:
# 设置DataFrame的index和columns的name属性
frame3.index.name = 'year'
frame3.columns.name = 'state'

In [125]:
frame3

state  Ben  Peter
year             
2000   NaN    1.0
2001   2.4    2.2
2002   2.9    3.3

In [126]:
# values属性返回数据
frame3.values

array([[nan, 1. ],
       [2.4, 2.2],
       [2.9, 3.3]])

In [128]:
# 各列的数据类型不同，会选择兼容所有列的数据类型
frame2.values

array([[2000, 'Ohio', 1.5, 10000.0],
       [2001, 'Ohio', 1.7, -1.5],
       [2002, 'Ohio', 3.6, -1.6],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan]], dtype=object)

## 索引对象

In [129]:
obj = Series(range(3),index=['a','b','c'])

In [130]:
obj

a    0
b    1
c    2
dtype: int64

In [131]:
index = obj.index

In [132]:
index

Index(['a', 'b', 'c'], dtype='object')

In [133]:
index[1:]

Index(['b', 'c'], dtype='object')

In [136]:
# index对象不可修改
#  index[1] = 'd'


In [138]:
index = pd.Index(np.arange(3))

In [140]:
index

Int64Index([0, 1, 2], dtype='int64')

In [141]:
obj2 = Series([1.5,-2,0],index=index)

In [144]:
obj2

0    1.5
1   -2.0
2    0.0
dtype: float64

In [145]:
frame3

state  Ben  Peter
year             
2000   NaN    1.0
2001   2.4    2.2
2002   2.9    3.3

In [147]:
frame2.index.is_unique

True