In [1]:
data1 = [1,2,3,4]

In [2]:
data1

[1, 2, 3, 4]

In [4]:
import numpy as np
arr1 = np.array(data1)

In [5]:
arr1

array([1, 2, 3, 4])

In [6]:
type(arr1)

numpy.ndarray

In [7]:
arr1.ndim

1

In [8]:
arr1.shape

(4,)

In [9]:
arr1.dtype

dtype('int32')

In [10]:
a = np.zeros(10)

In [11]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.empty((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])